"""Import unchanged audio-cmn recordings and generate the playback inventory."""

import argparse
import hashlib
import json
import shutil
import subprocess
import tempfile
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SOURCE = "https://github.com/hugolpz/audio-cmn"
REVISION = "ff9ed3d0c631195bd2c06f39450f3264c7124040"


def canonical_key(filename):
    key = Path(filename).stem.removeprefix("cmn-").removeprefix("_")
    if key.startswith(("lv", "nv")):
        key = key[0] + "ü" + key[2:]
    elif key.startswith(("jv", "qv", "xv")):
        key = key[0] + "u" + key[2:]
    return key


def blob_hash(data):
    return hashlib.sha1(b"blob " + str(len(data)).encode() + b"\0" + data).hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-repo", required=True, help="Local audio-cmn Git checkout (no working files required).")
    args = parser.parse_args()
    source_repo = Path(args.source_repo).resolve()
    source_tree = subprocess.check_output([
        "git", "-C", str(source_repo), "ls-tree", "-r", "-z", REVISION, "64k/syllabs",
    ])
    syllables = json.loads(subprocess.check_output([
        "node", "--input-type=module", "-e",
        "import {SYLLABLES} from './src/pinyin-data.js'; process.stdout.write(JSON.stringify(SYLLABLES.map(item => item.spelling)));",
    ], cwd=ROOT))
    allowed = {f"{syllable}{tone}" for syllable in syllables for tone in (1, 2, 3, 4)}
    recordings = {}
    for record in source_tree.split(b"\0"):
        if not record:
            continue
        attributes, source_path = record.decode("utf-8").split("\t", 1)
        _, kind, sha = attributes.split()
        key = canonical_key(source_path)
        if kind != "blob" or not source_path.endswith(".mp3") or key not in allowed:
            continue
        if key in recordings:
            raise RuntimeError(f"Duplicate canonical syllable: {key}")
        recordings[key] = {"source_path": source_path, "git_blob_sha1": sha}
    if not recordings:
        raise RuntimeError("No matching recordings found in the source repository.")

    cache = Path(tempfile.gettempdir()) / f"studypinyin-audio-cmn-{REVISION}"
    cache.mkdir(exist_ok=True)

    def download(key, metadata):
        cached = cache / Path(metadata["source_path"]).name
        if cached.exists() and blob_hash(cached.read_bytes()) == metadata["git_blob_sha1"]:
            return key, cached
        url = f"https://raw.githubusercontent.com/hugolpz/audio-cmn/{REVISION}/{metadata['source_path']}"
        for attempt in range(3):
            try:
                request = urllib.request.Request(url, headers={"User-Agent": "studypinyin-audio-import"})
                with urllib.request.urlopen(request, timeout=30) as response:
                    data = response.read()
                if blob_hash(data) != metadata["git_blob_sha1"]:
                    raise RuntimeError(f"Source checksum mismatch: {key}")
                cached.write_bytes(data)
                return key, cached
            except Exception:
                if attempt == 2:
                    raise
                time.sleep(attempt + 1)

    print(f"Downloading/verifying {len(recordings)} recordings from {REVISION}...", flush=True)
    downloaded = {}
    with ThreadPoolExecutor(max_workers=12) as executor:
        futures = [executor.submit(download, key, metadata) for key, metadata in recordings.items()]
        for future in as_completed(futures):
            key, cached = future.result()
            downloaded[key] = cached
            if len(downloaded) % 100 == 0 or len(downloaded) == len(recordings):
                print(f"Verified {len(downloaded)}/{len(recordings)}", flush=True)

    audio_root = (ROOT / "assets" / "audio").resolve()
    destination = (audio_root / "audio-cmn").resolve()
    if audio_root != ROOT / "assets" / "audio" or destination.parent != audio_root:
        raise RuntimeError("Audio destination must stay inside the project assets/audio directory.")
    destination.mkdir(exist_ok=True)
    inventory = {}
    for key, cached in sorted(downloaded.items()):
        filename = f"{key}.mp3"
        shutil.copyfile(cached, destination / filename)
        inventory[key] = filename
        recordings[key]["sha256"] = hashlib.sha256(cached.read_bytes()).hexdigest()
    for previous in destination.glob("*.mp3"):
        if previous.name not in inventory.values():
            previous.unlink()
    # Remove the replaced Kokoro clips only after every source recording is verified.
    for previous in audio_root.glob("*.mp3"):
        previous.unlink()

    (ROOT / "src" / "audio-data.js").write_text(
        "// Generated by scripts/import-audio-cmn.py; recordings by Chen Wang (CC BY-SA).\n"
        "export const AUDIO_FILES = Object.freeze(" + json.dumps(inventory, ensure_ascii=False, indent=2) + ");\n",
        encoding="utf-8",
    )
    manifest = {"source": SOURCE, "revision": REVISION, "author": "Chen Wang", "license": "CC BY-SA (version unspecified upstream)", "recordings": recordings}
    (audio_root / "audio-cmn-manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Imported {len(inventory)} unchanged recordings; generated src/audio-data.js.", flush=True)


if __name__ == "__main__":
    main()
